import "./globals.css";
import { Quicksand } from "next/font/google";
import { Providers } from "./providers";
import Loading from "./loading";
import { Suspense } from "react";
import Navbar from "./components/Navbar";
const quicksand = Quicksand({ subsets: ["latin"] });
import cookie from "js-cookie";
import { cookies } from "next/headers";
import Login from "./login/page";
export const metadata = {
  title: "Fe Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const cookieStore = cookies();
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col justify-between">
            <div className={quicksand.className}>
              <main>
                {cookieStore.get("login") ? (
                  <Suspense fallback={<Loading />}>
                    <div className="flex">{children}</div>
                  </Suspense>
                ) : (
                  <Suspense fallback={<Loading />}>
                    <div className="flex">
                      <Login />
                    </div>
                  </Suspense>
                )}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
