import "./globals.css";
import { Quicksand } from "next/font/google";
import { Providers } from "./providers";
import Loading from "./loading";
import { Suspense } from "react";
import Navbar from "./components/Navbar";
const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Fe Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col justify-between">
            <div className={quicksand.className}>
              <main>
                <Suspense fallback={<Loading />}>
                  <div className="flex">{children}</div>
                </Suspense>
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
